export enum PaymentState {
  INITIATED = "INITIATED",
  VALIDATING = "VALIDATING",
  QUEUED = "QUEUED",
  PROCESSING_SANDBOX = "PROCESSING_SANDBOX",
  PROCESSING_LIVE = "PROCESSING_LIVE",
  SUCCESS = "SUCCESS",
  FAILED = "FAILED",
  REVERSED = "REVERSED",
}

